name: Deploy history

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - history/**

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      NAME: history
      DIRECTORY: history

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ./scripts/cd/build-image.sh

      - name: Publish
        run: ./scripts/cd/push-image.sh

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      - name: Deploy
        run: ./scripts/cd/deploy.sh
