name: Deploy infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      - name: Deploy MongoDB
        run: kubectl apply -f ./scripts/cd/mongodb.yaml

      - name: Deploy Rabbit
        run: kubectl apply -f ./scripts/cd/rabbit.yaml
